projectFinder/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('projects/', include('projects.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

projects/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.projects, name='projects_list'),
    path('project/<str:pk>/', views.project, name='project_detail'),
    path('create-project/', views.createProject, name="create-project"),
    path('update-project/<str:pk>', views.updateProject, name='update-project'),
    path('delete-project/<str:pk>/', views.deleteProject, name='delete-project'),
    path('tag/<slug:tag_slug>', views.projects_by_tag, name="filter_by_tag"),

]

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.profiles, name="profiles"),
    path('profile/<str:pk>/', views.userProfile, name="user-profile"),
    path('skill/<slug:skill_slug>', views.profiles_by_skill, name="skill"),
]

projects/models.py
from django.db import models
from users.models import Profile
import uuid
from django.utils.text import slugify


#m2m model (Тэги для Проектов)
class Tag(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField()
    created_at = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def save(self, *args, **kwargs):
        value = self.name
        self.slug = slugify(value, allow_unicode=True)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


#Основная модель
class Project(models.Model):
    owner = models.ForeignKey(
        Profile, null=True, blank=True, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    image = models.ImageField(null=True, blank=True, default="project_images/default.jpg", upload_to='project_images')
    description = models.TextField(null=True, blank=True)
    tags = models.ManyToManyField(Tag, blank=True)
    total_votes = models.IntegerField(default=0, null=True, blank=True)
    votes_ratio = models.IntegerField(default=0, null=True, blank=True)
    demo_link = models.CharField(max_length=500, null=True, blank=True)
    source_link = models.CharField(max_length=500, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.title


#Отзыв Up Vote или же Down Vote связан с Project( one to many)
class Review(models.Model):
    VOTE_TYPE = (
        ('up', 'Up Vote'),
        ('down', 'Down Vote'),
    )

    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    review_text = models.TextField(null=True, blank=True)
    value = models.CharField(max_length=200, choices=VOTE_TYPE)
    created_at = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.value

users/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid


class Skill(models.Model):
    name = models.CharField(max_length=50, blank=True, null=True)
    slug = models.SlugField()
    description = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=True)

    def __str__(self):
        return self.name


class Profile(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=50, blank=True, null=True)
    email = models.EmailField(max_length=50, blank=True, null=True)
    username = models.CharField(max_length=50, blank=True, null=True)
    city = models.CharField(max_length=50, blank=True, null=True)
    intro = models.CharField(max_length=200, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    image = models.ImageField(
        null=True, blank=True, upload_to='profile_images', default="profile_images/default.jpg")
    skills = models.ManyToManyField(Skill, blank=True)
    github = models.CharField(max_length=100, blank=True, null=True)
    twitter = models.CharField(max_length=100, blank=True, null=True)
    linkedin = models.CharField(max_length=100, blank=True, null=True)
    youtube = models.CharField(max_length=100, blank=True, null=True)
    website = models.CharField(max_length=100, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        return self.username

    class Meta:
        ordering = ['created_at']

projects/forms.py
from django.forms import ModelForm
from .models import Project
from django import forms


class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = ['title', 'slug', 'tags', 'description', 'demo_link', 'source_link']
        labels = {
            'title': 'Название проекта',
            'slug': 'Слаг',
            'image': 'Изображение проекта',
            'tags': 'Тэги',
            'description': 'Описание проекта',
            'demo_link': 'Демо-версия',
            'source_link': 'Исходный код'
        }

        widgets = {
            'tags': forms.CheckboxSelectMultiple(),
        }

        def __init__(self, *args, **kwargs):
            super(ProjectForm, self).__init__(*args, **kwargs)
            for name, field in self.fields.items():
                field.widget.attrs.update({'class': 'input'})

projects/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Project, Tag, Review
from .forms import ProjectForm

# Create your views here.


def createProject(request):
    form = ProjectForm()
    if request.method == 'POST':
        form = ProjectForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('projects_list')
    context = {'form': form}
    return render(request, 'projects/project_form.html', context)


def updateProject(request, pk):
    project = Project.objects.get(id=pk)
    form = ProjectForm(instance=project)
    if request.method == 'POST':
        form = ProjectForm(request.POST, request.FILES, instance=project)
        if form.is_valid():
            form.save()
            return redirect('projects_list')
    context = {'form': form}
    return render(request, 'projects/project_form.html', context)


def deleteProject(request, pk):
    project = Project.objects.get(id=pk)
    if request.method == 'POST':
        project.delete()
        return redirect('projects_list')
    context = {'project': project}
    return render(request, 'projects/project-delete.html', context)


def projects_by_tag(request, tag_slug):
    tag = get_object_or_404(Tag, slug=tag_slug)
    projects = Project.objects.filter(tags__in=[tag])
    context = {'projects': projects}
    return render(request, 'projects/projects-list.html', context)


def project(request, pk):
    currentProject = Project.objects.get(id=str(pk))
    tags = currentProject.tags.all()
    return render(request, "projects/project-detail.html", {'project': currentProject})


def projects(request):
    ProjectsList = Project.objects.all()
    return render(request, "projects/projects-list.html", {'projects': ProjectsList})

users/views.py
from django.shortcuts import render, get_object_or_404
from .models import Skill, Profile


def profiles(request):
    profiles = Profile.objects.all()
    context = {'profiles': profiles}
    return render(request, 'users/profiles.html', context)


def userProfile(request, pk):
    profile = Profile.objects.get(id=pk)
    main_skills = profile.skills.all()[:2]
    extra_skills = profile.skills.all()[2:]
    context = {'profile': profile, 'main_skills': main_skills,
               "extra_skills": extra_skills}
    return render(request, 'users/user-profiles.html', context)


def profiles_by_skill(request, skill_slug):
    skill = get_object_or_404(Skill, slug=skill_slug)
    profiles = Profile.objects.filter(skills__in=[skill])
    context = {
        "profiles": profiles
    }
    return render(request, "users/profiles.html", context)

projects/templates/projects/project-delete.html
{% block content %}
<form action="" method="POST">
     {% csrf_token %}
     <p>Вы действительно хотите удалить "{{ project }}"?</p>
     <a href="{% url 'projects_list' %}">Отмена</a>
     <input type="submit" name="" value="Подтвердить удаление" />
</form>
{% endblock %}

projects/templates/projects/project-detail.html
{% extends 'base.html' %}

{% block content %}

<main class="singleProject my-md">
    <div class="container">
        <div class="layout">
            <div class="column column--1of3">
                <h3 class="singleProject__subtitle">Платформа и стек</h3>
                <div class="singleProject__toolStack">
                {% for tag in project.tags.all %}
                <a href="{% url 'filter_by_tag' tag.slug %}" class="tag tag--pill tag--sub tag--lg">{{tag}}</a>
                {% endfor %}               
                </div>

                {% if project.source_link %}
                <a class="singleProject__liveLink" href="{{ project.source_link }}" target="_blank"><i
                        class="im im-external-link"></i>Исходный код на GitHub
                </a>
                {% endif %}

                {% if project.demo_link %}
                <a class="singleProject__liveLink" href="{{ project.source_link }}" target="_blank"><i
                        class="im im-external-link"></i>Демо-сайт

                </a>
                {% endif %}

            </div>
            <div class="column column--2of3">
                <img class="singleProject__preview" src="{{ project.imageURL }}" alt="portfolio thumbnail" />
                <a href="{% url 'user-profile' project.owner.id %}"
                    class="singleProject__developer">{{ project.owner.name }}</a>
                <h2 class="singleProject__title">{{ project.title }}</h2>
                <h3 class="singleProject__subtitle">Информация о проекте</h3>
                <div class="singleProject__info">
                    {{ project.description }}
                </div>
                <div class="comments">
                    <h3 class="singleProject__subtitle">Оценки и отзывы</h3>
                    <h5 class="project--rating">
                    процент положительных отзывов: {{project.votes_ratio}}
                    </h5>
                    <h5 class="project--rating">
                    всего отзывов: {{project.total_votes}}
                    </h5>
                    {% if request.user.profile.id in project.reviewers %}
                    <p>Вы уже писали отзыв об этом проекте</p>

                    {% elif request.user.profile == project.owner %}
                    <p>Вы не можете оставлять отзывы к собственным проектам</p>

                    {% elif request.user.is_authenticated %}
                    <form class="form" action="{% url 'project_detail' project.id %}" method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="form__field">
                            <label for="formInput#textarea">{{ field.label }}</label>
                            {{field}}
                        </div>
                        {% endfor %}
                        <input class="btn btn--sub btn--lg" type="submit" value="Добавить отзыв" />
                    </form>
                    {% else %}
                    <a href="{% url 'login' %}?next={{ request.path }}">Войдите, чтобы оставить отзыв</a>
                    {% endif %}

                    <div class="commentList">
                        {% for review in project.review_set.all %}
                        {% if review.body %}
                        <div class="comment">
                            <a href="{% url 'user-profile' review.owner.id  %}">
                                <img class="avatar avatar--md" src="{{ review.owner.profile_image.url }}" alt="user" />
                            </a>


                            <div class="comment__details">
                                <a href="{% url 'user-profile' review.owner.id  %}"
                                    class="comment__author">{{ review.owner.name }}</a>
                                <p class="comment__info">{{ review.body|linebreaksbr }}</p>
                            </div>

                        </div>
                        {% endif %}
                        {% endfor %}

                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
</main>

{% endblock %}

projects/templates/projects/project_form.html
{% extends 'base.html' %}
{% block content %}

<main class="formPage my-xl">
 <div class="content-box">
     <div class="formWrapper">
         <a class="backButton" href="#"><i class="im im-angle-left"></i></a>
          <br>
          <form class="form" method="POST" enctype="multipart/form-data">
           {% csrf_token %}
           {% for field in form %}
           <div class="form__field">
            <label for="formInput#text">{{ field.label }}</label>
                 {{ field }}
           </div>
           {% endfor %}
           <div class="form__field">
            {% for tag in project.tags.all %}
             <div class="project-tag tag tag--pill tag--main" data-tag="{{ tag.id }}"
               data-project="{{ project.id }}">{{ tag.name }} &#215;</div>
            {% endfor %}
            </div>
            <div class="form__field">
             <label for="formInput#text">Теги</label>
             <textarea class="input" name="newtags" placeholder="Добавьте собственные теги, если их нет в списке"></textarea>
             </div>
             <input class="btn btn--sub btn--lg  my-md" type="submit" value="Сохранить" />
          </form>
    	 </div>
    </div>
</main>
{% endblock %}

projects/templates/projects/projects-list.html
{% extends 'base.html' %}
{% block content %}

<main class="projects">
    <section class="hero-section text-center">
        <div class="container container--narrow">
            <div class="hero-section__box">
                <h2>Поиск по <span>проектам</span></h2>
            </div>

            <div class="hero-section__search">
                <form id='searchForm' class="form" action="{% url 'projects_list' %}" method="get">
                    <div class="form__field">
                        <label for="formInput#search">Поиск по проектам </label>
                        <input class="input input--text" id="formInput#search" type="text" name="search_query"
                            placeholder="Поиск по названию/описанию проекта" value="{{ search_query }}" />
                    </div>

                    <input class="btn btn--sub btn--lg" type="submit" value="Найти" />
                </form>
            </div>
        </div>
    </section>
    <section class="projectsList">
        <div class="container">
            <div class="grid grid--three">

                {% for project in projects %}
                <div class="column">
                    <div class="card project">
                        <a href="{% url 'project_detail' project.slug %}" class="project">
                            <img class="project__thumbnail" src="{{ project.image.url }}" alt="скриншот проекта" />
                            <div class="card__body">
                                <h3 class="project__title">{{ project.title }}</h3>
                                <p><a class="project__author" href="{% url 'user-profile' project.owner %}">Разработчик:
                                        {{ project.owner.name }}</a>
                                </p>
                                <p class="project--rating">
                                    <span style="font-weight: bold;">положительных отзывов:</span>  {{ project.votes_ratio }}%
                                </p>
                                 <p class="project--rating">
                                    <span style="font-weight: bold;">всего отзывов:</span> {{ project.total_votes }}
                                </p>
                                <div class="project__tags">
                                    {% for tag in project.tags.all %}
                                    <a href="{% url 'filter_by_tag' tag.slug %}" class="tag tag--pill tag--main">{{tag}}</a>

                                    {% endfor %}

                                </div>
                            </div>
                        </a>
                    </div>
                </div>
                {% endfor %}

            </div>
        </div>
    </section>
</main>

{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://cdn.iconmonstr.com/1.3.0/css/iconmonstr-iconic-font.min.css" />
    <link rel="stylesheet" href="{% static 'uikit/styles/uikit.css' %}" />

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
   <link rel="stylesheet" href="{% static 'styles/main.css' %}" />
    <title>ITfinder - найди своего разработчика</title>

</head>

<body>
    {% include 'navbar.html' %}

    {% if messages %}

    {% for message in messages %}
    <div class="alert  alert--{{ message.tags }}">
        <p class="alert__message">{{message}}</p>
        <button class="alert__close">Закрыть</button>
    </div>

    {% endfor %}

    {% endif %}


    {% block content %}

    {% endblock content %}
    <div>
    <footer class="site-footer">
        <div class="footer-content">
            <h3>ProjectsMarketApp</h3>
            <p>Площадка, на которой каждый рекрутер сможет найти своего разрабочика.</p>
            <ul class="socials">
                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                <li><a href="#"><i class="fa fa-telegram"></i></a></li>
                <li><a href="#"><i class="fa fa-youtube"></i></a></li>
                <li><a href="#"><i class="fa fa-linkedin-square"></i></a></li>
            </ul>
        </div>
        <div class="footer-bottom">

                    <div class="footer-menu">
                      <ul class="f-menu">
                        <li><a href="">Главная</a></li>
                        <li><a href="">О проекте</a></li>
                        <li><a href="">Контакты</a></li>
                        <li><a href="">Блог</a></li>
                      </ul>
                    </div>
        </div>

    </footer>
    </div>
</body>
<script src="{% static 'uikit/app.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

</html>

templates/navbar.html
{% load static %}

<header class="header">
    <div class="container container--narrow">
        <a href="{% url 'profiles' %}"><span class="header__logo">PiPi Projects</span></a>
        <nav class="header__nav">
            <input type="checkbox" id="responsive-menu" />
            <label for="responsive-menu" class="toggle-menu">
                <span>Меню</span>
                <div class="toggle-menu__lines"></div>
            </label>
            <ul class="header__menu">
                <li class="header__menuItem"><a href="#">Разработчики</a></li>
                <li class="header__menuItem"><a href="{% url 'projects_list' %}">Проекты</a></li>



                {% if request.user.is_authenticated %}
                <li class="header__menuItem"><a href="#">Сообщения</a></li>
                <li class="header__menuItem"><a href="#">Мой аккаунт</a></li>
                <li class="header__menuItem"><a href="#" class="btn btn--sub">Выйти</a></li>
                {% else %}
                <li class="header__menuItem"><a href="#" class="btn btn--sub">Войти/зарегистрироваться</a></li>
                {% endif %}
            </ul>
        </nav>
    </div>
</header>

users/templates/users/profiles.html
{% extends 'base.html' %}

{% block content %}

<main class="home">
    <section class="hero-section text-center">
        <div class="container container--narrow">
            <div class="hero-section__box">
                <h2>Найти настоящего <span>профессионала</span></h2>
            </div>

            <div class="hero-section__search">

                <form id="searchForm" class="form" action="{% url 'profiles' %}" method="get">
                    <div class="form__field">
                        <label for="formInput#search">Поиск среди разработчиков </label>
                        <input class="input input--text" id="formInput#search" type="text" name="search_query"
                            value="" placeholder="Найти разработчика по имени, проекту, скиллу" />
                    </div>

                    <input class="btn btn--sub btn--lg" type="submit" value="Найти" />
                </form>

            </div>
        </div>
    </section>

    <section class="devlist">
        <div class="container">
            <div class="grid grid--three">

                {% for profile in profiles %}
                <div class="column card">
                    <div class="dev">
                        <a href="{% url 'user-profile' profile.id %}" class="card__body">
                            <div class="dev__profile">
                                <img class="avatar avatar--md" src="{{ profile.image.url }}" alt="image" />
                                <div class="dev__meta">
                                    <h3>{{ profile.name }}</h3>
                                    <h5>{{ profile.intro|slice:"60" }}</h5>
                                </div>
                            </div>
                            <p class="dev__info">{{ profile.bio|slice:"150" }}</p>
                            <div class="dev__skills">

                                {% for skill in profile.skills.all|slice:"3" %}
                                <a href="{% url 'skill' skill.slug %}" class="tag tag--pill tag--main">{{ skill }}</a>
                                {% endfor %}

                            </div>
                        </a>
                    </div>
                </div>
                {% endfor %}

            </div>
        </div>
    </section>
</main>

{% endblock content %}

users/templates/users/user-profiles.html
{% extends 'base.html' %}

{% block content %}

<main class="profile my-md">
    <div class="container">
        <div class="layout">
            <div class="column column--1of3">
                <div class="card text-center">
                    <div class="card__body dev">
                        <img class="avatar avatar--xl" src="{{ profile.image.url }}" />
                        <h2 class="dev__name">{{ profile.name }}</h2>
                        <p class="dev__title">{{ profile.intro }}</p>
                        <p class="dev__location">Город: {{ profile.city }}</p>
                        <ul class="dev__social">

                            {% if profile.github %}
                            <li>
                                <a title="Github" href="{{ profile.github }}" target="_blank"><i
                                        class="im im-github"></i></a>
                            </li>
                            {% endif %}


                            {% if profile.twitter %}
                            <li>
                                <a title="Twitter" href="{{ profile.twitter }}" target="_blank"><i
                                        class="im im-twitter"></i></a>
                            </li>
                            {% endif %}

                            {% if profile.linkedin %}
                            <li>
                                <a title="LinkedIn" href="{{ profile.linkedin }}" target="_blank"><i
                                        class="im im-linkedin"></i></a>
                            </li>
                            {% endif %}

                            {% if profile.website %}
                            <li>
                                <a title="Личный сайт" href="{{ profile.website }}" target="_blank"><i
                                        class="im im-globe"></i></a>
                            </li>
                            {% endif %}

                        </ul>
                        {% if request.user.profile.id != profile.id %}
                        <a href="#" class="btn btn--sub btn--lg">Написать сообщение </a>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="column column--2of3">
                <div class="devInfo">
                    <h3 class="devInfo__title">Обо мне</h3>
                    <p class="devInfo__about">{{ profile.bio }}</p>
                </div>
                <div class="devInfo">
                    <h3 class="devInfo__title">Стек и основные навыки</h3>
                    <div class="devInfo__skills">

                        {% for skill in main_skills %}
                        <div class="devSkill">
                            <h4 class="devSkill__title">{{ skill.name }}</h4>
                            <p class="devSkill__info">{{ skill.description }}</p>
                        </div>
                        {% endfor %}



                        <h3 class="devInfo__subtitle">Дополнительные навыки</h3>
                        <div class="devInfo__otherSkills">

                            {% for skill in extra_skills %}
                            <span class="tag tag--pill tag--sub tag--lg">
                                <small>{{ skill }}</small>
                            </span>
                            {% endfor %}

                        </div>
                    </div>
                </div>
                <div class="devInfo">
                    <h3 class="devInfo__title">Проекты</h3>
                    <div class="grid grid--two">
                        {% for project in profile.project_set.all %}
                        <div class="column">
                            <div class="card project">
                                <a href="{% url 'project' project.id %}" class="project">
                                    <img class="project__thumbnail" src="{{ project.image.url }}"
                                        alt="project thumbnail" />
                                    <div class="card__body">
                                        <h3 class="project__title">{{ project.title }}</h3>
                                        <p><a class="project__author"
                                                href="{% url 'user-profile' project.owner.id %}">Разработчик:
                                                {{ project.owner.name }}</a>
                                        </p>
                                        <p class="project--rating">
                                            <span style="font-weight: bold;">положительные отзывы</span>{{ project.votes_ratio }}% всего отзывов{{ project.total_votes }}
                                        </p>
                                        <div class="project__tags">

                                            {% for tag in project.tags.all %}
                                            <span class="tag tag--pill tag--main">
                                                <small>{{tag}}</small>
                                            </span>
                                            {% endfor %}

                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                        {% endfor %}


                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

{% endblock content %}